{{- range .Values.sites }}
{{- if (lookup "v1" "Namespace" "" .svc.namespace) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .host }}
  namespace: {{ .svc.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.tls.issuerName }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: {{ .svc.protocol }}
    {{- if .acl }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .acl }}
    nginx.ingress.kubernetes.io/custom-http-errors: "403"
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ $.Values.tls.secretName }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .svc.name }}
            port: 
              number: {{ .svc.port }}
---
{{- end }}
{{- end }}
