{{- if .Values.gateway.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-public-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https-public
  hostnames:
    - {{ .Values.gateway.host }}
  rules:
    - backendRefs:
        - name: {{ (index .Values.services 0).name }}
          port: {{ (index (index .Values.services 0).ports 0).port }}
---
{{- end }}
{{- if .Values.gateway.mtls.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-mtls-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https-mtls
  hostnames:
    - {{ .Values.gateway.host }}
  rules:
    - backendRefs:
        - name: {{ (index .Values.services 0).name }}
          port: {{ (index (index .Values.services 0).ports 0).port }}
{{- end }}