{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}  
{{- end }}
